
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zqwhhpyrknihoufzvmou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpxd2hocHlya25paG91Znp2bW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MDczMTQsImV4cCI6MjA2MjE4MzMxNH0.7XN_CgvW9W9UjUo9cPHzYJhabgBgvsa6mY20OBYXssE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
